name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code!
      uses: actions/checkout@v3
      with:
        - fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        echo "Iniciando loggin"
        docker login -u $DOCKER_USER -P $DOCKER_PASSWORD
        echo "Fin de loggin"
        


        
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
